- name: variables
  hosts: local
  connection: local
  vars: #play level variables
    COURSE: "DevOpswith AWS"
    DURATION: 120HRS
    TRAINER: Sivakumar
  tasks: 
  - name: print the variables
    vars: #task level variables
      COURSE: Ansible
    ansible.builtin.debug:
      msg: {{COURSE}}
    
