- name: variables
  hosts: local
  connection: local
  vars:
    COURSE: "Hema DevOps"
    DURATION: 1month
    TRAINER: Hemalatha
  tasks:
  - name: print the variables
    ansible.builtin.debug:
      msg: "Course is {{COURSE}} and duration is {{DURATION}} and trainer is {{TRAINER}}" 