- name: variables from files
  hosts: local
  connection: local
  vars_files:
  - variables.yaml
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "Course is {{COURSE}}"
